### ISSUE TITLE
Add option to stop vite (dev server) in case codegen fails

### ISSUE THREAD

**Issue by dahei** [danielwaltz/vite-plugin-graphql-codegen#15]
It would be beneficial to have an option to let the vite process (and dev server) fail and stop in case the code generation failed for whatever reason.

The same is already implemented for the `runOnBuild` option.

**Current situation:** 

Even if the codegen fails I end up on the sucessful vite "ready" state because the codegen error messages are already cleared from the terminal. So if you don't pay close attention you might not notice the failed codegen at all.

<img width="285" alt="CleanShot 2023-04-05 at 11 59 57@2x" src="https://user-images.githubusercontent.com/2070820/230048439-affa9d38-327f-4d6a-a238-d044ffe59332.png">

Maybe it is just adding `&& isServe` here to that condition: https://github.com/danielwaltz/vite-plugin-graphql-codegen/blob/main/src/index.ts#L148 or introduce a new option to give a choice whether to bail out or ignoring the failed codegen.

**Comment by danielwaltz** [comment]
Good idea! I remember it feeling important to not nuke vite immediately because at least in my case using docker for local development, the API endpoint I'm using to generate isn't immediately available/running.

I think adding options to fail on start/build would be the perfect fit, and in order to not cause breaking issues I'll probably default start to `false` and build the `true`!

**Comment by danielwaltz** [comment]
@dahei Ok, added two new config options for this! `throwOnStart` and `throwOnBuild`. Let me know if anything looks off or isn't working!

**Comment by dahei** [comment]
@danielwaltz works like a charm - thanks for the quick response 😄
